const { v4: uuidv4 } = require('uuid');

class InMemoryStore {
  constructor() {
    this.users = [
      {
        id: 'user-hardik',
        name: 'Hardik',
        email: 'hardik@ddu.ac.in',
        password: '$2a$10$abcdefghijklmnopqrstuvwxyz123456', // dummy hashed
        campusOrCity: 'DDU, Nadiad, Gujarat',
        majorOrBio: 'Computer Engineering (CE) | DDU 2026',
        reputation: 240,
        joinedCommunityIds: ['c1', 'c2', 'c3'],
        badges: ['Community Contributor', 'Verified DDU Student', 'Top Answerer'],
        isCollegeVerified: true,
      },
    ];

    this.communities = [
      {
        id: 'c1',
        name: 'DDU Students',
        description: 'Official Community for all DDU students. Announcements, exams, syllabus & general campus queries.',
        regionId: 'region-ddu',
        regionName: 'DDU, Nadiad, Gujarat',
        category: 'Official Community',
        memberCount: 1200,
        questionCount: 142,
        iconEmoji: '🎓',
        bannerColorHex: 0xFF6366F1,
        isJoined: true,
        rules: [
          'Be respectful and helpful to all DDU peers.',
          'Keep discussions relevant to academics and campus life.',
          'No ragging, hate speech, or exam cheating material.',
        ],
      },
      {
        id: 'c2',
        name: 'DDU Hostel',
        description: 'Life & Help for students staying in boys/girls hostels and nearby PGs.',
        regionId: 'region-ddu',
        regionName: 'DDU, Nadiad, Gujarat',
        category: 'Life & Help',
        memberCount: 340,
        questionCount: 78,
        iconEmoji: '🏠',
        bannerColorHex: 0xFF10B981,
        isJoined: true,
        rules: [
          'Verified hostel and flatmate updates.',
          'Respect hostel timings and privacy.',
        ],
      },
      {
        id: 'c3',
        name: 'DDU Sports',
        description: 'Play. Compete. Win. Cricket, volleyball, table tennis, badminton & annual sports meet.',
        regionId: 'region-ddu',
        regionName: 'DDU, Nadiad, Gujarat',
        category: 'Play. Compete. Win.',
        memberCount: 210,
        questionCount: 45,
        iconEmoji: '⚽',
        bannerColorHex: 0xFFF97316,
        isJoined: true,
        rules: [
          'Ground booking coordination.',
          'Good sportsmanship at all times.',
        ],
      },
      {
        id: 'c4',
        name: 'DDU ACM & Coding Club',
        description: 'Competitive programming, web/app hackathons, and placement interview prep.',
        regionId: 'region-ddu',
        regionName: 'DDU, Nadiad, Gujarat',
        category: 'Tech & Dev',
        memberCount: 890,
        questionCount: 110,
        iconEmoji: '💻',
        bannerColorHex: 0xFF8B5CF6,
        isJoined: false,
      },
      {
        id: 'c5',
        name: 'DDU Canteens & Foodies',
        description: 'Best lunch spots, tea/coffee stalls, street food reviews near campus.',
        regionId: 'region-ddu',
        regionName: 'DDU, Nadiad, Gujarat',
        category: 'Food & Dining',
        memberCount: 540,
        questionCount: 62,
        iconEmoji: '🍜',
        bannerColorHex: 0xFFEC4899,
        isJoined: false,
      },
    ];

    this.questions = [
      {
        id: 'q1',
        title: 'Which canteen is best for lunch?',
        content: 'Looking for good hygienic vegetarian lunch options near the engineering block or main gate.',
        communityId: 'c1',
        communityName: 'DDU Students',
        regionId: 'region-ddu',
        regionName: 'DDU, Nadiad, Gujarat',
        authorId: 'u-anon-1',
        authorName: 'Anonymous',
        isAnonymous: true,
        anonymousPseudonym: 'Anonymous',
        tags: ['Canteen', 'Food', 'DDU'],
        upvotes: 8,
        views: 340,
        createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
        replies: [
          {
            id: 'r1',
            questionId: 'q1',
            content: 'The canteen behind the library has fresh thali at ₹60, highly recommended!',
            authorId: 'u-senior',
            authorName: 'Senior Peer',
            upvotes: 5,
            createdAt: new Date(Date.now() - 1.3 * 3600 * 1000).toISOString(),
            isAccepted: true,
          },
        ],
        isUpvotedByMe: false,
        isBookmarked: false,
        isResolved: true,
      },
      {
        id: 'q2',
        title: 'What are the sports facilities in DDU?',
        content: 'Can first year students use the basketball court and gym in the evening? What are the registration steps?',
        communityId: 'c3',
        communityName: 'DDU Sports',
        regionId: 'region-ddu',
        regionName: 'DDU, Nadiad, Gujarat',
        authorId: 'u-rahul',
        authorName: 'Rahul',
        authorBadge: 'Community Helper',
        isAnonymous: false,
        tags: ['Sports', 'Gym', 'Basketball'],
        upvotes: 14,
        views: 480,
        createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
        replies: [
          {
            id: 'r2',
            questionId: 'q2',
            content: 'Yes! Basketball and volleyball grounds are open 4:30 PM to 7:00 PM. Just carry your DDU ID card.',
            authorId: 'u-coach',
            authorName: 'Sports Secretary',
            upvotes: 9,
            createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
            isAccepted: true,
          },
        ],
        isUpvotedByMe: true,
        isBookmarked: true,
        isResolved: false,
      },
      {
        id: 'q3',
        title: 'What are the important rules for first year students?',
        content: 'Just joined DDU! What is the minimum attendance requirement and lab manual submission rules?',
        communityId: 'c1',
        communityName: 'DDU Students',
        regionId: 'region-ddu',
        regionName: 'DDU, Nadiad, Gujarat',
        authorId: 'u-anon-2',
        authorName: 'Anonymous',
        isAnonymous: true,
        anonymousPseudonym: 'Anonymous',
        tags: ['FirstYear', 'Attendance', 'Academics'],
        upvotes: 22,
        views: 790,
        createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
        replies: [
          {
            id: 'r3',
            questionId: 'q3',
            content: 'Maintain at least 75% attendance strictly. Also make sure to get your lab files signed weekly to avoid midsem stress.',
            authorId: 'u-ta',
            authorName: 'Final Year Student',
            upvotes: 16,
            createdAt: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
            isAccepted: true,
          },
        ],
        isUpvotedByMe: true,
        isBookmarked: false,
        isResolved: true,
      },
    ];

    this.rooms = [
      {
        id: 'room-c1',
        title: 'DDU Students Official Chat',
        subtitle: '1.2K members • Active now',
        avatarEmoji: '🎓',
        communityId: 'c1',
        isGroup: true,
        lastMessage: 'Tomorrow library is open till 8 PM for midsem prep.',
        lastMessageTime: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
        unreadCount: 3,
        isOnline: true,
        participantIds: ['u-rahul', 'user-hardik'],
      },
      {
        id: 'room-c2',
        title: 'DDU Hostel Group',
        subtitle: '340 hostellers online',
        avatarEmoji: '🏠',
        communityId: 'c2',
        isGroup: true,
        lastMessage: 'Mess menu for dinner has been updated on notice board.',
        lastMessageTime: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
        unreadCount: 0,
        isOnline: true,
        participantIds: ['user-hardik'],
      },
      {
        id: 'room-dm-rahul',
        title: 'Rahul (Community Helper)',
        subtitle: 'Active now',
        avatarEmoji: '👨‍🎓',
        isGroup: false,
        lastMessage: 'Hey Hardik, are you coming to the basketball court today?',
        lastMessageTime: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        unreadCount: 1,
        isOnline: true,
        participantIds: ['u-rahul', 'user-hardik'],
      },
    ];

    this.messages = {
      'room-c1': [
        {
          id: 'm1',
          roomId: 'room-c1',
          senderId: 'u-rahul',
          senderName: 'Rahul',
          content: 'Hey everyone, what is the timetable for mid-sem exam?',
          timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
          isMine: false,
        },
        {
          id: 'm2',
          roomId: 'room-c1',
          senderId: 'user-hardik',
          senderName: 'Hardik',
          content: 'It was posted on the department notice board and student portal yesterday.',
          timestamp: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
          isMine: true,
        },
        {
          id: 'm3',
          roomId: 'room-c1',
          senderId: 'u-rahul',
          senderName: 'Rahul',
          content: 'Tomorrow library is open till 8 PM for midsem prep.',
          timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
          isMine: false,
        },
      ],
    };
  }
}

const store = new InMemoryStore();
module.exports = store;
